import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Part-load curve type: kW/ton at each load point
interface PartLoadCurve {
  pct100: number;
  pct75: number;
  pct50: number;
  pct25: number;
}

interface ChillerData {
  manufacturer: string;
  model_number: string;
  equipment_category: string;
  equipment_subcategory: string;
  compressor_type: string;
  cooling_capacity_tons: number;
  cooling_capacity_kw: number;
  eer: number;
  cop: number;
  iplv: number;
  part_load_curve: PartLoadCurve;
  evap_pressure_drop_ft: number;
  cond_pressure_drop_ft: number | null;
  chw_delta_t_f: number;
  cw_delta_t_f: number | null;
  waterflow_l_s: number;
  voltage: string;
  phases: number;
  full_load_amps: number;
  lra: number;
  power_input_kw: number;
  refrigerant_type: string;
  weight_kg: number;
  sound_power_level_db: number;
  saso_certified: boolean;
  ashrae_compliant: boolean;
  ahri_certified: boolean;
  ahri_cert_number: string;
  list_price_sar: number;
  lead_time_weeks: number;
  is_active: boolean;
}

// Helper to calculate CHW flow in L/s from tons and delta-T
const calcFlowLps = (tons: number, deltaT: number): number => {
  // GPM = (tons * 24) / deltaT, then convert to L/s
  const gpm = (tons * 24) / deltaT;
  return Math.round(gpm * 0.0631 * 10) / 10;
};

// Carrier Chillers
const carrierChillers: ChillerData[] = [
  // Water-Cooled Centrifugal - 19XR Series
  {
    manufacturer: "Carrier",
    model_number: "19XR-0350",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 350,
    cooling_capacity_kw: 1231,
    eer: 6.40,
    cop: 6.40,
    iplv: 10.20,
    part_load_curve: { pct100: 0.548, pct75: 0.478, pct50: 0.420, pct25: 0.382 },
    evap_pressure_drop_ft: 14.8,
    cond_pressure_drop_ft: 12.5,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(350, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 285,
    lra: 1425,
    power_input_kw: 192,
    refrigerant_type: "R-134a",
    weight_kg: 5890,
    sound_power_level_db: 85,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-350C",
    list_price_sar: 485000,
    lead_time_weeks: 14,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "19XR-0500",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 500,
    cooling_capacity_kw: 1758,
    eer: 6.50,
    cop: 6.50,
    iplv: 10.50,
    part_load_curve: { pct100: 0.530, pct75: 0.465, pct50: 0.410, pct25: 0.370 },
    evap_pressure_drop_ft: 16.5,
    cond_pressure_drop_ft: 14.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(500, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 385,
    lra: 1950,
    power_input_kw: 265,
    refrigerant_type: "R-134a",
    weight_kg: 7620,
    sound_power_level_db: 87,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-500C",
    list_price_sar: 625000,
    lead_time_weeks: 16,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "19XR-0700",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 700,
    cooling_capacity_kw: 2462,
    eer: 6.60,
    cop: 6.60,
    iplv: 10.80,
    part_load_curve: { pct100: 0.515, pct75: 0.450, pct50: 0.395, pct25: 0.355 },
    evap_pressure_drop_ft: 18.2,
    cond_pressure_drop_ft: 15.8,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(700, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 520,
    lra: 2600,
    power_input_kw: 360,
    refrigerant_type: "R-134a",
    weight_kg: 9450,
    sound_power_level_db: 89,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-700C",
    list_price_sar: 820000,
    lead_time_weeks: 18,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "19XR-1000",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 1000,
    cooling_capacity_kw: 3517,
    eer: 6.70,
    cop: 6.70,
    iplv: 11.00,
    part_load_curve: { pct100: 0.500, pct75: 0.438, pct50: 0.382, pct25: 0.342 },
    evap_pressure_drop_ft: 20.5,
    cond_pressure_drop_ft: 17.8,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(1000, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 725,
    lra: 3625,
    power_input_kw: 500,
    refrigerant_type: "R-134a",
    weight_kg: 12800,
    sound_power_level_db: 91,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-1000C",
    list_price_sar: 1150000,
    lead_time_weeks: 20,
    is_active: true,
  },
  // Water-Cooled Screw - 30XW Series
  {
    manufacturer: "Carrier",
    model_number: "30XW-0150",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 150,
    cooling_capacity_kw: 528,
    eer: 5.80,
    cop: 5.80,
    iplv: 9.20,
    part_load_curve: { pct100: 0.605, pct75: 0.535, pct50: 0.475, pct25: 0.428 },
    evap_pressure_drop_ft: 12.5,
    cond_pressure_drop_ft: 10.8,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(150, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 145,
    lra: 725,
    power_input_kw: 91,
    refrigerant_type: "R-134a",
    weight_kg: 2850,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-150S",
    list_price_sar: 285000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "30XW-0200",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 200,
    cooling_capacity_kw: 703,
    eer: 5.90,
    cop: 5.90,
    iplv: 9.40,
    part_load_curve: { pct100: 0.595, pct75: 0.525, pct50: 0.465, pct25: 0.418 },
    evap_pressure_drop_ft: 13.2,
    cond_pressure_drop_ft: 11.5,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(200, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 185,
    lra: 925,
    power_input_kw: 119,
    refrigerant_type: "R-134a",
    weight_kg: 3420,
    sound_power_level_db: 83,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-200S",
    list_price_sar: 345000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "30XW-0280",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 280,
    cooling_capacity_kw: 985,
    eer: 6.00,
    cop: 6.00,
    iplv: 9.60,
    part_load_curve: { pct100: 0.585, pct75: 0.515, pct50: 0.455, pct25: 0.408 },
    evap_pressure_drop_ft: 14.5,
    cond_pressure_drop_ft: 12.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(280, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 248,
    lra: 1240,
    power_input_kw: 164,
    refrigerant_type: "R-134a",
    weight_kg: 4280,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-280S",
    list_price_sar: 425000,
    lead_time_weeks: 14,
    is_active: true,
  },
  // Air-Cooled Screw - 30XA Series
  {
    manufacturer: "Carrier",
    model_number: "30XA-0100",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 100,
    cooling_capacity_kw: 352,
    eer: 3.20,
    cop: 3.20,
    iplv: 5.80,
    part_load_curve: { pct100: 1.098, pct75: 0.920, pct50: 0.785, pct25: 0.678 },
    evap_pressure_drop_ft: 11.5,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(100, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 165,
    lra: 825,
    power_input_kw: 110,
    refrigerant_type: "R-410A",
    weight_kg: 3250,
    sound_power_level_db: 88,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-100A",
    list_price_sar: 225000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "30XA-0150",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 150,
    cooling_capacity_kw: 528,
    eer: 3.30,
    cop: 3.30,
    iplv: 6.00,
    part_load_curve: { pct100: 1.065, pct75: 0.895, pct50: 0.762, pct25: 0.658 },
    evap_pressure_drop_ft: 12.8,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(150, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 235,
    lra: 1175,
    power_input_kw: 160,
    refrigerant_type: "R-410A",
    weight_kg: 4580,
    sound_power_level_db: 90,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-150A",
    list_price_sar: 315000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "Carrier",
    model_number: "30XA-0200",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 200,
    cooling_capacity_kw: 703,
    eer: 3.40,
    cop: 3.40,
    iplv: 6.20,
    part_load_curve: { pct100: 1.035, pct75: 0.870, pct50: 0.742, pct25: 0.640 },
    evap_pressure_drop_ft: 14.2,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(200, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 305,
    lra: 1525,
    power_input_kw: 207,
    refrigerant_type: "R-410A",
    weight_kg: 5920,
    sound_power_level_db: 92,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-200A",
    list_price_sar: 395000,
    lead_time_weeks: 12,
    is_active: true,
  },
  // Air-Cooled Scroll - 30RB Series
  {
    manufacturer: "Carrier",
    model_number: "30RB-040",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 40,
    cooling_capacity_kw: 141,
    eer: 3.00,
    cop: 3.00,
    iplv: 5.20,
    part_load_curve: { pct100: 1.170, pct75: 1.005, pct50: 0.875, pct25: 0.765 },
    evap_pressure_drop_ft: 8.5,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(40, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 72,
    lra: 360,
    power_input_kw: 47,
    refrigerant_type: "R-410A",
    weight_kg: 1420,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-CAR-040R",
    list_price_sar: 85000,
    lead_time_weeks: 6,
    is_active: true,
  },
];

// Trane Chillers
const traneChillers: ChillerData[] = [
  // Water-Cooled Centrifugal - CVHF Series
  {
    manufacturer: "Trane",
    model_number: "CVHF-0300",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 300,
    cooling_capacity_kw: 1055,
    eer: 6.35,
    cop: 6.35,
    iplv: 10.10,
    part_load_curve: { pct100: 0.555, pct75: 0.485, pct50: 0.428, pct25: 0.390 },
    evap_pressure_drop_ft: 14.2,
    cond_pressure_drop_ft: 12.0,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(300, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 248,
    lra: 1240,
    power_input_kw: 166,
    refrigerant_type: "R-134a",
    weight_kg: 5120,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-300C",
    list_price_sar: 445000,
    lead_time_weeks: 14,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "CVHF-0400",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 400,
    cooling_capacity_kw: 1407,
    eer: 6.45,
    cop: 6.45,
    iplv: 10.35,
    part_load_curve: { pct100: 0.542, pct75: 0.472, pct50: 0.415, pct25: 0.378 },
    evap_pressure_drop_ft: 15.5,
    cond_pressure_drop_ft: 13.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(400, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 325,
    lra: 1625,
    power_input_kw: 218,
    refrigerant_type: "R-134a",
    weight_kg: 6450,
    sound_power_level_db: 86,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-400C",
    list_price_sar: 545000,
    lead_time_weeks: 16,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "CVHF-0600",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 600,
    cooling_capacity_kw: 2110,
    eer: 6.55,
    cop: 6.55,
    iplv: 10.65,
    part_load_curve: { pct100: 0.525, pct75: 0.458, pct50: 0.402, pct25: 0.365 },
    evap_pressure_drop_ft: 17.5,
    cond_pressure_drop_ft: 15.0,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(600, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 465,
    lra: 2325,
    power_input_kw: 322,
    refrigerant_type: "R-134a",
    weight_kg: 8650,
    sound_power_level_db: 88,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-600C",
    list_price_sar: 745000,
    lead_time_weeks: 18,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "CVHF-0800",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 800,
    cooling_capacity_kw: 2814,
    eer: 6.65,
    cop: 6.65,
    iplv: 10.90,
    part_load_curve: { pct100: 0.510, pct75: 0.445, pct50: 0.390, pct25: 0.352 },
    evap_pressure_drop_ft: 19.2,
    cond_pressure_drop_ft: 16.5,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(800, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 605,
    lra: 3025,
    power_input_kw: 423,
    refrigerant_type: "R-134a",
    weight_kg: 10850,
    sound_power_level_db: 90,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-800C",
    list_price_sar: 985000,
    lead_time_weeks: 20,
    is_active: true,
  },
  // Water-Cooled Screw - RTWD Series
  {
    manufacturer: "Trane",
    model_number: "RTWD-0150",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 150,
    cooling_capacity_kw: 528,
    eer: 5.75,
    cop: 5.75,
    iplv: 9.10,
    part_load_curve: { pct100: 0.612, pct75: 0.540, pct50: 0.480, pct25: 0.432 },
    evap_pressure_drop_ft: 12.2,
    cond_pressure_drop_ft: 10.5,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(150, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 148,
    lra: 740,
    power_input_kw: 92,
    refrigerant_type: "R-134a",
    weight_kg: 2780,
    sound_power_level_db: 81,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-150S",
    list_price_sar: 278000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "RTWD-0200",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 200,
    cooling_capacity_kw: 703,
    eer: 5.85,
    cop: 5.85,
    iplv: 9.30,
    part_load_curve: { pct100: 0.600, pct75: 0.530, pct50: 0.470, pct25: 0.422 },
    evap_pressure_drop_ft: 13.0,
    cond_pressure_drop_ft: 11.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(200, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 190,
    lra: 950,
    power_input_kw: 120,
    refrigerant_type: "R-134a",
    weight_kg: 3350,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-200S",
    list_price_sar: 338000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "RTWD-0300",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 300,
    cooling_capacity_kw: 1055,
    eer: 5.95,
    cop: 5.95,
    iplv: 9.50,
    part_load_curve: { pct100: 0.590, pct75: 0.520, pct50: 0.460, pct25: 0.412 },
    evap_pressure_drop_ft: 14.2,
    cond_pressure_drop_ft: 12.0,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(300, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 275,
    lra: 1375,
    power_input_kw: 177,
    refrigerant_type: "R-134a",
    weight_kg: 4650,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-300S",
    list_price_sar: 465000,
    lead_time_weeks: 14,
    is_active: true,
  },
  // Air-Cooled Screw - RTAC Series
  {
    manufacturer: "Trane",
    model_number: "RTAC-0100",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 100,
    cooling_capacity_kw: 352,
    eer: 3.15,
    cop: 3.15,
    iplv: 5.70,
    part_load_curve: { pct100: 1.115, pct75: 0.935, pct50: 0.798, pct25: 0.690 },
    evap_pressure_drop_ft: 11.2,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(100, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 168,
    lra: 840,
    power_input_kw: 112,
    refrigerant_type: "R-410A",
    weight_kg: 3180,
    sound_power_level_db: 87,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-100A",
    list_price_sar: 218000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "RTAC-0150",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 150,
    cooling_capacity_kw: 528,
    eer: 3.25,
    cop: 3.25,
    iplv: 5.90,
    part_load_curve: { pct100: 1.082, pct75: 0.908, pct50: 0.775, pct25: 0.670 },
    evap_pressure_drop_ft: 12.5,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(150, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 240,
    lra: 1200,
    power_input_kw: 162,
    refrigerant_type: "R-410A",
    weight_kg: 4480,
    sound_power_level_db: 89,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-150A",
    list_price_sar: 308000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "Trane",
    model_number: "RTAC-0200",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 200,
    cooling_capacity_kw: 703,
    eer: 3.35,
    cop: 3.35,
    iplv: 6.10,
    part_load_curve: { pct100: 1.050, pct75: 0.882, pct50: 0.752, pct25: 0.650 },
    evap_pressure_drop_ft: 13.8,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(200, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 310,
    lra: 1550,
    power_input_kw: 210,
    refrigerant_type: "R-410A",
    weight_kg: 5780,
    sound_power_level_db: 91,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-200A",
    list_price_sar: 388000,
    lead_time_weeks: 12,
    is_active: true,
  },
  // Air-Cooled Scroll - CGAM Series
  {
    manufacturer: "Trane",
    model_number: "CGAM-050",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 50,
    cooling_capacity_kw: 176,
    eer: 2.95,
    cop: 2.95,
    iplv: 5.10,
    part_load_curve: { pct100: 1.192, pct75: 1.025, pct50: 0.892, pct25: 0.782 },
    evap_pressure_drop_ft: 8.8,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(50, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 88,
    lra: 440,
    power_input_kw: 60,
    refrigerant_type: "R-410A",
    weight_kg: 1680,
    sound_power_level_db: 83,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-TRA-050R",
    list_price_sar: 98000,
    lead_time_weeks: 6,
    is_active: true,
  },
];

// York Chillers
const yorkChillers: ChillerData[] = [
  // Water-Cooled Centrifugal - YK Series
  {
    manufacturer: "York",
    model_number: "YK-0350",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 350,
    cooling_capacity_kw: 1231,
    eer: 6.38,
    cop: 6.38,
    iplv: 10.15,
    part_load_curve: { pct100: 0.550, pct75: 0.480, pct50: 0.422, pct25: 0.385 },
    evap_pressure_drop_ft: 14.5,
    cond_pressure_drop_ft: 12.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(350, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 282,
    lra: 1410,
    power_input_kw: 193,
    refrigerant_type: "R-134a",
    weight_kg: 5750,
    sound_power_level_db: 85,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-350C",
    list_price_sar: 475000,
    lead_time_weeks: 14,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YK-0450",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 450,
    cooling_capacity_kw: 1583,
    eer: 6.48,
    cop: 6.48,
    iplv: 10.40,
    part_load_curve: { pct100: 0.538, pct75: 0.468, pct50: 0.412, pct25: 0.375 },
    evap_pressure_drop_ft: 15.8,
    cond_pressure_drop_ft: 13.5,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(450, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 358,
    lra: 1790,
    power_input_kw: 244,
    refrigerant_type: "R-134a",
    weight_kg: 7020,
    sound_power_level_db: 87,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-450C",
    list_price_sar: 585000,
    lead_time_weeks: 16,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YK-0650",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 650,
    cooling_capacity_kw: 2286,
    eer: 6.58,
    cop: 6.58,
    iplv: 10.72,
    part_load_curve: { pct100: 0.520, pct75: 0.452, pct50: 0.398, pct25: 0.360 },
    evap_pressure_drop_ft: 17.8,
    cond_pressure_drop_ft: 15.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(650, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 495,
    lra: 2475,
    power_input_kw: 348,
    refrigerant_type: "R-134a",
    weight_kg: 9120,
    sound_power_level_db: 89,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-650C",
    list_price_sar: 785000,
    lead_time_weeks: 18,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YK-0900",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 900,
    cooling_capacity_kw: 3165,
    eer: 6.68,
    cop: 6.68,
    iplv: 10.95,
    part_load_curve: { pct100: 0.505, pct75: 0.440, pct50: 0.385, pct25: 0.348 },
    evap_pressure_drop_ft: 19.8,
    cond_pressure_drop_ft: 17.0,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(900, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 675,
    lra: 3375,
    power_input_kw: 474,
    refrigerant_type: "R-134a",
    weight_kg: 11950,
    sound_power_level_db: 91,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-900C",
    list_price_sar: 1085000,
    lead_time_weeks: 20,
    is_active: true,
  },
  // Water-Cooled Screw - YVWA Series
  {
    manufacturer: "York",
    model_number: "YVWA-0150",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 150,
    cooling_capacity_kw: 528,
    eer: 5.78,
    cop: 5.78,
    iplv: 9.15,
    part_load_curve: { pct100: 0.608, pct75: 0.538, pct50: 0.478, pct25: 0.430 },
    evap_pressure_drop_ft: 12.4,
    cond_pressure_drop_ft: 10.6,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(150, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 146,
    lra: 730,
    power_input_kw: 91,
    refrigerant_type: "R-134a",
    weight_kg: 2820,
    sound_power_level_db: 81,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-150S",
    list_price_sar: 280000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YVWA-0200",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 200,
    cooling_capacity_kw: 703,
    eer: 5.88,
    cop: 5.88,
    iplv: 9.35,
    part_load_curve: { pct100: 0.598, pct75: 0.528, pct50: 0.468, pct25: 0.420 },
    evap_pressure_drop_ft: 13.1,
    cond_pressure_drop_ft: 11.3,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(200, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 188,
    lra: 940,
    power_input_kw: 120,
    refrigerant_type: "R-134a",
    weight_kg: 3380,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-200S",
    list_price_sar: 342000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YVWA-0280",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 280,
    cooling_capacity_kw: 985,
    eer: 5.98,
    cop: 5.98,
    iplv: 9.55,
    part_load_curve: { pct100: 0.588, pct75: 0.518, pct50: 0.458, pct25: 0.410 },
    evap_pressure_drop_ft: 14.3,
    cond_pressure_drop_ft: 12.0,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(280, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 252,
    lra: 1260,
    power_input_kw: 165,
    refrigerant_type: "R-134a",
    weight_kg: 4320,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-280S",
    list_price_sar: 432000,
    lead_time_weeks: 14,
    is_active: true,
  },
  // Air-Cooled Screw - YCAL Series
  {
    manufacturer: "York",
    model_number: "YCAL-0100",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 100,
    cooling_capacity_kw: 352,
    eer: 3.18,
    cop: 3.18,
    iplv: 5.75,
    part_load_curve: { pct100: 1.105, pct75: 0.928, pct50: 0.792, pct25: 0.685 },
    evap_pressure_drop_ft: 11.4,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(100, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 166,
    lra: 830,
    power_input_kw: 111,
    refrigerant_type: "R-410A",
    weight_kg: 3220,
    sound_power_level_db: 88,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-100A",
    list_price_sar: 222000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YCAL-0140",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 140,
    cooling_capacity_kw: 492,
    eer: 3.28,
    cop: 3.28,
    iplv: 5.95,
    part_load_curve: { pct100: 1.072, pct75: 0.902, pct50: 0.770, pct25: 0.665 },
    evap_pressure_drop_ft: 12.2,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(140, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 222,
    lra: 1110,
    power_input_kw: 150,
    refrigerant_type: "R-410A",
    weight_kg: 4280,
    sound_power_level_db: 89,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-140A",
    list_price_sar: 295000,
    lead_time_weeks: 10,
    is_active: true,
  },
  // Air-Cooled Scroll - YLAA Series
  {
    manufacturer: "York",
    model_number: "YLAA-045",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 45,
    cooling_capacity_kw: 158,
    eer: 2.98,
    cop: 2.98,
    iplv: 5.15,
    part_load_curve: { pct100: 1.180, pct75: 1.015, pct50: 0.882, pct25: 0.772 },
    evap_pressure_drop_ft: 8.6,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(45, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 80,
    lra: 400,
    power_input_kw: 53,
    refrigerant_type: "R-410A",
    weight_kg: 1550,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-045R",
    list_price_sar: 92000,
    lead_time_weeks: 6,
    is_active: true,
  },
  {
    manufacturer: "York",
    model_number: "YLAA-065",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 65,
    cooling_capacity_kw: 229,
    eer: 3.05,
    cop: 3.05,
    iplv: 5.30,
    part_load_curve: { pct100: 1.152, pct75: 0.990, pct50: 0.860, pct25: 0.752 },
    evap_pressure_drop_ft: 9.2,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(65, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 112,
    lra: 560,
    power_input_kw: 75,
    refrigerant_type: "R-410A",
    weight_kg: 2150,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-YRK-065R",
    list_price_sar: 125000,
    lead_time_weeks: 6,
    is_active: true,
  },
];

// Daikin Chillers
const daikinChillers: ChillerData[] = [
  // Water-Cooled Centrifugal - Navigator Series
  {
    manufacturer: "Daikin",
    model_number: "NAV-0300",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 300,
    cooling_capacity_kw: 1055,
    eer: 6.42,
    cop: 6.42,
    iplv: 10.25,
    part_load_curve: { pct100: 0.548, pct75: 0.478, pct50: 0.420, pct25: 0.382 },
    evap_pressure_drop_ft: 14.0,
    cond_pressure_drop_ft: 11.8,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(300, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 245,
    lra: 1225,
    power_input_kw: 164,
    refrigerant_type: "R-134a",
    weight_kg: 5050,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-300C",
    list_price_sar: 455000,
    lead_time_weeks: 14,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "NAV-0450",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 450,
    cooling_capacity_kw: 1583,
    eer: 6.52,
    cop: 6.52,
    iplv: 10.45,
    part_load_curve: { pct100: 0.535, pct75: 0.465, pct50: 0.408, pct25: 0.372 },
    evap_pressure_drop_ft: 15.5,
    cond_pressure_drop_ft: 13.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(450, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 355,
    lra: 1775,
    power_input_kw: 243,
    refrigerant_type: "R-134a",
    weight_kg: 6850,
    sound_power_level_db: 86,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-450C",
    list_price_sar: 575000,
    lead_time_weeks: 16,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "NAV-0600",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 600,
    cooling_capacity_kw: 2110,
    eer: 6.62,
    cop: 6.62,
    iplv: 10.75,
    part_load_curve: { pct100: 0.518, pct75: 0.450, pct50: 0.395, pct25: 0.358 },
    evap_pressure_drop_ft: 17.2,
    cond_pressure_drop_ft: 14.8,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(600, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 460,
    lra: 2300,
    power_input_kw: 319,
    refrigerant_type: "R-134a",
    weight_kg: 8520,
    sound_power_level_db: 88,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-600C",
    list_price_sar: 755000,
    lead_time_weeks: 18,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "NAV-0800",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-centrifugal",
    compressor_type: "centrifugal",
    cooling_capacity_tons: 800,
    cooling_capacity_kw: 2814,
    eer: 6.72,
    cop: 6.72,
    iplv: 11.00,
    part_load_curve: { pct100: 0.502, pct75: 0.435, pct50: 0.382, pct25: 0.345 },
    evap_pressure_drop_ft: 19.0,
    cond_pressure_drop_ft: 16.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(800, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 600,
    lra: 3000,
    power_input_kw: 419,
    refrigerant_type: "R-134a",
    weight_kg: 10680,
    sound_power_level_db: 90,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-800C",
    list_price_sar: 995000,
    lead_time_weeks: 20,
    is_active: true,
  },
  // Water-Cooled Screw - AWS Series
  {
    manufacturer: "Daikin",
    model_number: "AWS-0120",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 120,
    cooling_capacity_kw: 422,
    eer: 5.72,
    cop: 5.72,
    iplv: 9.05,
    part_load_curve: { pct100: 0.615, pct75: 0.545, pct50: 0.485, pct25: 0.435 },
    evap_pressure_drop_ft: 11.8,
    cond_pressure_drop_ft: 10.2,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(120, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 120,
    lra: 600,
    power_input_kw: 74,
    refrigerant_type: "R-134a",
    weight_kg: 2450,
    sound_power_level_db: 80,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-120S",
    list_price_sar: 245000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "AWS-0180",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 180,
    cooling_capacity_kw: 633,
    eer: 5.82,
    cop: 5.82,
    iplv: 9.25,
    part_load_curve: { pct100: 0.605, pct75: 0.535, pct50: 0.475, pct25: 0.425 },
    evap_pressure_drop_ft: 12.8,
    cond_pressure_drop_ft: 11.0,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(180, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 172,
    lra: 860,
    power_input_kw: 109,
    refrigerant_type: "R-134a",
    weight_kg: 3150,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-180S",
    list_price_sar: 318000,
    lead_time_weeks: 12,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "AWS-0250",
    equipment_category: "chiller",
    equipment_subcategory: "water-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 250,
    cooling_capacity_kw: 879,
    eer: 5.92,
    cop: 5.92,
    iplv: 9.45,
    part_load_curve: { pct100: 0.595, pct75: 0.525, pct50: 0.465, pct25: 0.415 },
    evap_pressure_drop_ft: 13.8,
    cond_pressure_drop_ft: 11.8,
    chw_delta_t_f: 10,
    cw_delta_t_f: 10,
    waterflow_l_s: calcFlowLps(250, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 230,
    lra: 1150,
    power_input_kw: 149,
    refrigerant_type: "R-134a",
    weight_kg: 4050,
    sound_power_level_db: 83,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-250S",
    list_price_sar: 398000,
    lead_time_weeks: 14,
    is_active: true,
  },
  // Air-Cooled Screw - AGZ Series
  {
    manufacturer: "Daikin",
    model_number: "AGZ-080",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 80,
    cooling_capacity_kw: 281,
    eer: 3.12,
    cop: 3.12,
    iplv: 5.65,
    part_load_curve: { pct100: 1.128, pct75: 0.948, pct50: 0.810, pct25: 0.700 },
    evap_pressure_drop_ft: 10.8,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(80, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 138,
    lra: 690,
    power_input_kw: 90,
    refrigerant_type: "R-410A",
    weight_kg: 2680,
    sound_power_level_db: 86,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-080A",
    list_price_sar: 185000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "AGZ-120",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 120,
    cooling_capacity_kw: 422,
    eer: 3.22,
    cop: 3.22,
    iplv: 5.85,
    part_load_curve: { pct100: 1.092, pct75: 0.918, pct50: 0.785, pct25: 0.678 },
    evap_pressure_drop_ft: 11.8,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(120, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 198,
    lra: 990,
    power_input_kw: 131,
    refrigerant_type: "R-410A",
    weight_kg: 3850,
    sound_power_level_db: 88,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-120A",
    list_price_sar: 258000,
    lead_time_weeks: 10,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "AGZ-160",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-screw",
    compressor_type: "screw",
    cooling_capacity_tons: 160,
    cooling_capacity_kw: 563,
    eer: 3.32,
    cop: 3.32,
    iplv: 6.05,
    part_load_curve: { pct100: 1.058, pct75: 0.890, pct50: 0.760, pct25: 0.658 },
    evap_pressure_drop_ft: 13.0,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(160, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 255,
    lra: 1275,
    power_input_kw: 170,
    refrigerant_type: "R-410A",
    weight_kg: 4920,
    sound_power_level_db: 90,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-160A",
    list_price_sar: 328000,
    lead_time_weeks: 12,
    is_active: true,
  },
  // Air-Cooled Scroll - EWAD Series
  {
    manufacturer: "Daikin",
    model_number: "EWAD-035",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 35,
    cooling_capacity_kw: 123,
    eer: 2.92,
    cop: 2.92,
    iplv: 5.05,
    part_load_curve: { pct100: 1.205, pct75: 1.035, pct50: 0.902, pct25: 0.792 },
    evap_pressure_drop_ft: 8.2,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(35, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 65,
    lra: 325,
    power_input_kw: 42,
    refrigerant_type: "R-410A",
    weight_kg: 1280,
    sound_power_level_db: 80,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-035R",
    list_price_sar: 75000,
    lead_time_weeks: 6,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "EWAD-055",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 55,
    cooling_capacity_kw: 193,
    eer: 3.02,
    cop: 3.02,
    iplv: 5.25,
    part_load_curve: { pct100: 1.165, pct75: 1.000, pct50: 0.870, pct25: 0.762 },
    evap_pressure_drop_ft: 9.0,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(55, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 98,
    lra: 490,
    power_input_kw: 64,
    refrigerant_type: "R-410A",
    weight_kg: 1880,
    sound_power_level_db: 82,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-055R",
    list_price_sar: 108000,
    lead_time_weeks: 6,
    is_active: true,
  },
  {
    manufacturer: "Daikin",
    model_number: "EWAD-075",
    equipment_category: "chiller",
    equipment_subcategory: "air-cooled-scroll",
    compressor_type: "scroll",
    cooling_capacity_tons: 75,
    cooling_capacity_kw: 264,
    eer: 3.10,
    cop: 3.10,
    iplv: 5.42,
    part_load_curve: { pct100: 1.135, pct75: 0.972, pct50: 0.845, pct25: 0.742 },
    evap_pressure_drop_ft: 9.8,
    cond_pressure_drop_ft: null,
    chw_delta_t_f: 10,
    cw_delta_t_f: null,
    waterflow_l_s: calcFlowLps(75, 10),
    voltage: "380V",
    phases: 3,
    full_load_amps: 128,
    lra: 640,
    power_input_kw: 85,
    refrigerant_type: "R-410A",
    weight_kg: 2420,
    sound_power_level_db: 84,
    saso_certified: true,
    ashrae_compliant: true,
    ahri_certified: true,
    ahri_cert_number: "AHRI-2024-DAI-075R",
    list_price_sar: 138000,
    lead_time_weeks: 6,
    is_active: true,
  },
];

// Combine all chillers
const allChillers = [
  ...carrierChillers,
  ...traneChillers,
  ...yorkChillers,
  ...daikinChillers,
];

Deno.serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error("Missing Supabase environment variables");
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check for force parameter from request body
    const body = await req.json().catch(() => ({}));
    const force = body.force === true;

    // Check if chillers already exist
    const { count, error: countError } = await supabase
      .from("equipment_catalog")
      .select("*", { count: "exact", head: true })
      .eq("equipment_category", "chiller");

    if (countError) {
      throw countError;
    }

    if (count && count > 0 && !force) {
      return new Response(
        JSON.stringify({
          seeded: false,
          message: `Chiller catalog already contains ${count} entries. Use ?force=true to reseed.`,
          existingCount: count,
        }),
        {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 200,
        }
      );
    }

    // If force, delete existing chillers first
    if (force && count && count > 0) {
      const { error: deleteError } = await supabase
        .from("equipment_catalog")
        .delete()
        .eq("equipment_category", "chiller");

      if (deleteError) {
        throw deleteError;
      }
    }

    // Insert all chillers
    const { data, error: insertError } = await supabase
      .from("equipment_catalog")
      .insert(allChillers)
      .select();

    if (insertError) {
      throw insertError;
    }

    // Calculate counts by manufacturer
    const byManufacturer = allChillers.reduce((acc, chiller) => {
      acc[chiller.manufacturer] = (acc[chiller.manufacturer] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    // Calculate counts by type
    const byType = allChillers.reduce((acc, chiller) => {
      acc[chiller.equipment_subcategory] = (acc[chiller.equipment_subcategory] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return new Response(
      JSON.stringify({
        seeded: true,
        count: data?.length || 0,
        byManufacturer,
        byType,
        message: `Successfully seeded ${data?.length || 0} AHRI-certified chiller models`,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error: unknown) {
    console.error("Error seeding chiller catalog:", error);
    const errorMessage = error instanceof Error ? error.message : "Failed to seed chiller catalog";
    return new Response(
      JSON.stringify({
        error: errorMessage,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
